package shaverma.frontend;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class LoginForm extends BaseApplicationForm {
    private JButton loginButton;
    private JPasswordField passwordInput;
    private JPanel loginForm;
    private JTextField loginInput;
    private JComboBox roleSelector;

    public LoginForm(Application app) {
        super(app);
        initRoleSelector();
        initLoginButton();
    }

    private void initRoleSelector() {
        roleSelector.addItem(new ComboBoxItem<String>("MANAGER", "Manager"));
        roleSelector.addItem(new ComboBoxItem<String>("PROVIDER", "Provider"));
        roleSelector.addItem(new ComboBoxItem<String>("CLIENT", "Client"));
    }

    private void initLoginButton() {
        loginButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                String loginString = loginInput.getText();
                ComboBoxItem<String> selectedRole = (ComboBoxItem<String>) roleSelector.getSelectedItem();
                if (selectedRole != null && getService().login(loginString, selectedRole.getValue())) {
                    switch (selectedRole.getValue()) {
                        case "MANAGER":
                            break;
                        case "PROVIDER":
                            break;
                        case "CLIENT":
                            switchToForm(new ClientForm(getApp()));
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Неверное имя пользователя");
                }
            }
        });
    }

    @Override
    JPanel createFormPanel() {
        return loginForm;
    }

    @Override
    String getTitle() {
        return "Войти";
    }

    @Override
    Dimension getSize() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginForm = new JPanel();
        loginForm.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), -1, -1));
        loginInput = new JTextField();
        loginInput.setText("");
        loginForm.add(loginInput, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Роль");
        loginForm.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        roleSelector = new JComboBox();
        loginForm.add(roleSelector, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Войти");
        loginForm.add(loginButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Имя");
        loginForm.add(label2, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginForm;
    }
}
